/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    CardBaseContent: typeof import('./src/components/CardBaseContent.vue')['default']
    CardSingleContent: typeof import('./src/components/CardSingleContent.vue')['default']
    CardStackedContent: typeof import('./src/components/CardStackedContent.vue')['default']
    CardToolsContent: typeof import('./src/components/CardToolsContent.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    Dialog: typeof import('primevue/dialog')['default']
    DialogBaseFilters: typeof import('./src/components/DialogBaseFilters.vue')['default']
    DialogBaseFullscreen: typeof import('./src/components/DialogBaseFullscreen.vue')['default']
    DialogBaseSettings: typeof import('./src/components/DialogBaseSettings.vue')['default']
    FileUpload: typeof import('primevue/fileupload')['default']
    Filterbar: typeof import('./src/components/Filterbar.vue')['default']
    FloatLabel: typeof import('primevue/floatlabel')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Listbox: typeof import('primevue/listbox')['default']
    MostLikedRow: typeof import('./src/components/MostLikedRow.vue')['default']
    MultiSelect: typeof import('primevue/multiselect')['default']
    NavigationBase: typeof import('./src/components/NavigationBase.vue')['default']
    NavigationSaved: typeof import('./src/components/NavigationSaved.vue')['default']
    NavigationUploads: typeof import('./src/components/NavigationUploads.vue')['default']
    Paginator: typeof import('primevue/paginator')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    QuickCollectionModal: typeof import('./src/components/QuickCollectionModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTop: typeof import('primevue/scrolltop')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SingleMetadata: typeof import('./src/components/SingleMetadata.vue')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SkeletonBaseContent: typeof import('./src/components/SkeletonBaseContent.vue')['default']
    SpeedDial: typeof import('primevue/speeddial')['default']
    Tag: typeof import('primevue/tag')['default']
    Textarea: typeof import('primevue/textarea')['default']
  }
  export interface ComponentCustomProperties {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
